#!/usr/bin/env python3
"""
Generate one SLURM script per dataset for the San José processing pass.

Each scripts/cluster/process/{accession}.sbatch is a thin #SBATCH wrapper that
execs _process_runner.sh — so every dataset's job spec (resources, name) is
individually visible, editable and resubmittable, while the run logic lives in
one shared script.

Usage:
  python scripts/cluster/gen_process_scripts.py PXD050342 PXD038273
  python scripts/cluster/gen_process_scripts.py --list accessions.txt
"""
import argparse
import sys
from pathlib import Path

OUT = Path("scripts/cluster/process")
RUNNER = ("/lustre/project/ki-proanagi/dateschn/claudius-proteomics"
          "/scripts/cluster/_process_runner.sh")

TEMPLATE = """#!/bin/bash
#SBATCH --account=ki-proanagi
#SBATCH --partition=ki-parallel
#SBATCH --cpus-per-task=128
#SBATCH --mem=240G
#SBATCH --time=2-00:00:00
#SBATCH --job-name=cp-{acc}
#SBATCH --output=/lustre/project/ki-proanagi/dateschn/logs/proc-%x-%j.log
#
# Process {acc} — San José runner, Sage + FragPipe (DIA-NN deferred).
# Generated by scripts/cluster/gen_process_scripts.py.
exec {runner} {acc}
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("accessions", nargs="*", help="PRIDE accessions")
    ap.add_argument("--list", type=Path, help="file with one accession per line")
    args = ap.parse_args()

    accs = list(args.accessions)
    if args.list and args.list.exists():
        accs += [ln.split()[0] for ln in args.list.read_text().splitlines()
                 if ln.strip() and not ln.lstrip().startswith("#")]
    accs = sorted(set(accs))
    if not accs:
        ap.error("no accessions given (positional args or --list)")

    OUT.mkdir(parents=True, exist_ok=True)
    for acc in accs:
        (OUT / f"{acc}.sbatch").write_text(TEMPLATE.format(acc=acc, runner=RUNNER))
    print(f"wrote {len(accs)} script(s) to {OUT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
